spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shopify_reai_sync
    username: postgres
    password: postgres
shopify:
  api-key: ${SHOPIFY_API_KEY}
  api-secret: ${SHOPIFY_API_SECRET}
  app-base-url: https://shopify.reai.no
reai:
  api-base-url: http://localhost:8080/api
  token-url: http://localhost:8080/oauth2/token